import {preset} from './scenarios.js';
const $=id=>document.getElementById(id);
let worker,seq=0,current=null,input=preset(),playing=false,last=0,t=0;
const fail=message=>{$('status').textContent='Prediction unavailable';$('explanation').textContent=message;$('readout').replaceChildren();$('map').replaceChildren();$('download').disabled=true;current=null;};
function send(){if(!worker)return;$('download').disabled=true;current=null;seq++;try{worker.postMessage({id:seq,input});}catch(e){fail(e.message);}}
try{worker=new Worker('./worker.js',{type:'module'});worker.onerror=()=>fail('The prediction worker failed. Serve the project over HTTP and confirm ai/artifacts/model.json is present.');worker.onmessage=({data})=>{if(data.id!==seq)return;if(data.error){fail(data.error);return;}current=data;render();};send();}catch(e){fail(e.message);}
function metric(label,value,detail){const div=document.createElement('div');div.className='metric';const l=document.createElement('div');l.className='label';l.textContent=label;const v=document.createElement('div');v.className='value';v.textContent=value;const d=document.createElement('div');d.className='detail';d.textContent=detail;div.append(l,v,d);return div;}
function render(){const r=current.result;$('status').textContent=r.status.replaceAll('_',' ');$('explanation').textContent=current.assistant.text;$('reasons').textContent=r.reasons.join(' · ');$('download').disabled=false;
 $('readout').replaceChildren(metric('Predicted contact',r.nominal.ttc===null?'None in horizon':r.nominal.ttc.toFixed(2)+' s','Constant-velocity envelope intersection'),metric('Remaining timing margin',r.timingMargin===null?'—':Math.round(r.timingMargin*1000)+' ms','After an assumed 320 ms budget'),metric('Experimental ML score',r.learnedScore.toFixed(3),'Synthetic-trained; NOT a real-world probability'),metric('Fit residual',r.fitError.toFixed(3)+' m','Motion inconsistency indicator'),metric('Hardware deployment','DISABLED','No actuator connection; no safety qualification'));
 const x=v=>350+v*16,y=v=>220-v*16;let svg='';for(let v=-20;v<=20;v+=5){svg+=`<path d="M${x(v)} 20V410 M20 ${y(v)}H680" stroke="#243c49"/><text x="${x(v)+2}" y="430">${v}</text>`;}
 svg+='<text x="15" y="20">Forward / y (m)</text><text x="550" y="430">Lateral / x (m)</text><circle cx="350" cy="220" r="6" fill="#62ddc4"/><text x="360" y="213">Wearer</text>';
 svg+=`<circle cx="350" cy="220" r="${r.radius*16}" fill="none" stroke="#62ddc4" stroke-dasharray="5 5"/><circle cx="350" cy="220" r="${(r.radius+r.uncertainty)*16}" fill="none" stroke="#4b7372" stroke-dasharray="2 5"/>`;
 svg+=`<polyline points="${input.samples.map(s=>`${x(s.x)},${y(s.y)}`).join(' ')}" fill="none" stroke="#b9c5ca" stroke-width="3"/><path d="M${x(r.x)} ${y(r.y)}L${x(r.x+r.vx*3)} ${y(r.y+r.vy*3)}" stroke="#edb96b" stroke-width="2" stroke-dasharray="6 4"/><circle cx="${x(r.x)}" cy="${y(r.y)}" r="8" fill="#edb96b"/>`;$('map').innerHTML=svg;
}
function reset(){playing=false;t=0;$('play').textContent='▶ Replay';$('scrub').value=0;$('clock').textContent='0.00 s';input=preset($('preset').value);send();}
$('preset').onchange=reset;$('scrub').oninput=()=>{playing=false;$('play').textContent='▶ Replay';t=Number($('scrub').value);$('clock').textContent=t.toFixed(2)+' s';input=preset($('preset').value,t);send();};
$('play').onclick=()=>{if(t>=1.4)t=0;playing=!playing;$('play').textContent=playing?'Ⅱ Pause':'▶ Replay';};
function tick(now){if(playing&&now-last>=100){t=Math.min(1.4,t+.05);$('scrub').value=t;$('clock').textContent=t.toFixed(2)+' s';input=preset($('preset').value,t);send();last=now;if(t>=1.4){playing=false;$('play').textContent='↻ Replay';}}requestAnimationFrame(tick);}requestAnimationFrame(tick);
$('upload').onchange=async()=>{playing=false;$('play').textContent='▶ Replay';const f=$('upload').files[0];if(!f)return;if(f.size>100000){seq++;fail('Track files must be under 100 KB.');return;}try{input=JSON.parse(await f.text());send();}catch(e){seq++;fail('Invalid track file: '+e.message);}};
$('download').onclick=()=>{if(!current)return;const url=URL.createObjectURL(new Blob([JSON.stringify({input,...current},null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='cocoon-forecast.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
const answers={limits:'This model inspects existing metric tracks. It cannot detect objects from video, observe blind spots, prove injury reduction, or authorize inflation. The learned score was trained only on generated trajectories.',materials:'Candidate features: staggered chamber coverage inspired by pangolin scales; damage-tolerant connections inspired by ironclad beetles; layered tear/puncture reinforcement inspired by arapaima. Their benefit for this suit still needs physical testing.',data:'nuScenes is a candidate for metric trajectory/radar research; PIE adds pedestrian behavior context; KFall supports a separate fall branch. None is a validated wearable collision dataset. Their data are not included in this prototype.'};
document.querySelectorAll('[data-topic]').forEach(b=>b.onclick=()=>{const answer=$('answer');answer.replaceChildren();answer.append(document.createTextNode(b.dataset.topic==='decision'?(current?.assistant.text||'Load a valid track first.'):answers[b.dataset.topic]));const a=document.createElement('a');a.href='../docs/'+(b.dataset.topic==='decision'||b.dataset.topic==='limits'?'AI-MODEL-CARD.md':'AI-RESEARCH.md');a.textContent=' Read supporting notes ↗';answer.append(a);});
fetch('./artifacts/evaluation.json').then(r=>{if(!r.ok)throw new Error();return r.json();}).then(r=>{$('evidence').textContent=`${r.splits.train.sessions} training / ${r.splits.validation.sessions} validation / ${r.splits.test.sessions} test sessions. Entirely synthetic. Real-world accuracy: not established.`;}).catch(()=>{$('evidence').textContent='Evaluation artifact unavailable. No accuracy claim can be shown.';});
