import {defaults,modules,simulate,sample,fraction,csv} from './model.js';
import {createScene} from './scene.js';
const $=id=>document.getElementById(id);let p={...defaults},r=simulate(p),t=0,playing=false,last=0,view;
try{view=createScene($('scene'),(mode,reason)=>{$('renderer-status').textContent=mode;$('renderer-status').title=reason;if(reason)console.warn('Renderer fallback:',reason);});}catch(e){$('webgl-error').textContent='Scene initialization failed: '+e.message;$('webgl-error').hidden=false;console.error('Scene initialization failed',e);}
$('compatibility').onclick=()=>view?.useSoftware();
const fields=[['height','Vertical drop',.3,6,.1,'m'],['speed','Vehicle speed',10,60,1,'km/h'],['transfer','Assumed velocity transfer',.1,.7,.05,'ratio'],['mass','Dummy mass',45,120,1,'kg'],['stature','Dummy stature',1.5,2,.01,'m']];
const deployment=[['latency','Detection + command delay',0,600,10,'ms'],['fill','Inflation duration',40,500,10,'ms'],['thickness','Maximum cushion stroke',.05,.35,.01,'m'],['pressure','Effective gauge pressure',5,80,1,'kPa'],['area','Effective contact area',.02,.2,.01,'m²']];
function fieldsHTML(list){return list.map(([id,label,min,max,step,unit])=>`<label class="field" id="field-${id}"><span>${label}<output id="value-${id}">${p[id]} ${unit}</output></span><input type="range" id="${id}" min="${min}" max="${max}" step="${step}" value="${p[id]}" data-unit="${unit}"></label>`).join('');}
$('parameters').innerHTML=fieldsHTML(fields);$('deployment').innerHTML=fieldsHTML(deployment);
for(const [id] of [...fields,...deployment])$(id).addEventListener('input',()=>{p[id]=Number($(id).value);rebuild();});
for(const id of ['orientation','failure'])$(id).addEventListener('change',()=>{p[id]=$(id).value;rebuild();});$('legs').addEventListener('change',()=>{p.legs=$('legs').checked;rebuild();});
document.querySelectorAll('[data-scenario]').forEach(b=>b.onclick=()=>{p.scenario=b.dataset.scenario;rebuild();});
function metric(label,value,unit,detail,warn=false){return `<div class="metric ${warn?'warn':''}"><div class="label">${label}</div><span class="value">${value}</span><span class="unit">${unit}</span><div class="detail">${detail}</div></div>`;}
function rebuild(){r=simulate(p);t=0;playing=false;$('play').textContent='▶ Run experiment';$('timeline').max=r.end;
 for(const [id,,,,,unit] of [...fields,...deployment]){$(id).value=p[id];$('value-'+id).textContent=p[id]+' '+unit;}
 $('orientation').value=p.orientation;$('failure').value=p.failure;$('legs').checked=p.legs;
 $('field-height').hidden=p.scenario==='car';$('field-speed').hidden=$('field-transfer').hidden=p.scenario!=='car';
 document.querySelectorAll('[data-scenario]').forEach(b=>b.classList.toggle('active',b.dataset.scenario===p.scenario));
 $('scene-title').textContent=p.scenario==='fall'?'BUILDING / DROP RIG':'PEDESTRIAN / POST-STRIKE STUDY';
 $('scenario-note').textContent=p.scenario==='fall'?'Fixed contact pose beside a building. Drop is vertical travel to first ground contact; no harness dynamics.':'Initial car contact at 0.60 s. Post-strike trajectory is assumed, not a solved vehicle collision.';
 $('metrics').innerHTML=metric('Ground-contact speed',r.vy.toFixed(2),'m/s','Vertical component only')+metric('Incident kinetic energy',Math.round(r.energy).toLocaleString(),'J',p.scenario==='car'?'Includes assumed horizontal motion':'Whole dummy, translational energy')+metric('Full-inflation timing margin',r.blocked?'INHIBITED':Math.round(r.margin),r.blocked?'':'ms','Ground contact minus delay and fill time',r.margin<0||r.blocked)+metric('Normal energy beyond cushion work',Math.round(r.residual).toLocaleString(),'J','Constant-pressure screening estimate',r.residual>0)+metric('Estimated total deployed volume',Math.round(r.volume),'L','Illustrative geometry budget; not CAD-derived');
 $('interpretation').textContent=`${Math.round(r.ready*100)}% inflation in the ${modules.find(m=>m.id===r.selected).name.toLowerCase()} module at ground contact. Available stroke: ${(r.stroke*100).toFixed(1)} cm. Assumed P·A·s capacity: ${Math.round(r.capacity)} J against ${Math.round(r.normalEnergy)} J normal incident energy. ${r.residual>0?'This configuration exhausts its modeled cushion work before stopping the body.':'The simplified energy budget fits; local injury and peak loads remain unknown.'} ${p.scenario==='car'?'Horizontal energy is not absorbed by this normal-contact model.':''}`;
 $('chambers').innerHTML=modules.map(m=>`<div class="chamber"><div class="chamber-top"><span>${m.name} <span class="muted">${m.group}</span></span><span id="status-${m.id}"></span></div><div class="bar"><span id="bar-${m.id}"></span></div></div>`).join('');
 view?.setResult(r);draw();}
function chart(){const X=x=>42+x/r.end*637,Y=f=>88-f*67;const pts=Array.from({length:121},(_,i)=>{const time=i*r.end/120;return `${X(time)},${Y(fraction(p,time,r.selected))}`;}).join(' ');$('chart').innerHTML=`<text x="2" y="16">%</text><text x="7" y="27">100</text><text x="17" y="91">0</text><path d="M42 21H679M42 88H679" stroke="#2b414e"/><polyline points="${pts}" fill="none" stroke="#62ddc4" stroke-width="2.5"/><path d="M${X(r.impact)} 12V94" stroke="#edb96b" stroke-dasharray="4 4"/><path d="M${X(t)} 14V94" stroke="#e8eef1"/><text x="42" y="108">0</text><text x="637" y="108">${r.end.toFixed(2)}</text><text x="315" y="120">Time (s)</text>`;}
function draw(){const s=sample(r,t);$('time').textContent=t.toFixed(3)+' s';$('timeline').value=t;$('phase').textContent=s.phase;for(const m of modules){const f=fraction(p,t,m.id);$('status-'+m.id).textContent=m.id==='legs'&&!p.legs?'Omitted':p.failure===m.id?'FAULT':`${Math.round(f*100)}%`;$('bar-'+m.id).style.width=(f*100)+'%';}chart();view?.update(t);}
$('play').onclick=()=>{if(t>=r.end)t=0;playing=!playing;$('play').textContent=playing?'Ⅱ Pause':'▶ Run experiment';};$('timeline').oninput=()=>{playing=false;$('play').textContent='▶ Run experiment';t=Number($('timeline').value);draw();};$('reset').onclick=()=>{p={...defaults};rebuild();};$('camera').onclick=()=>view?.resetCamera();
function frame(now){if(playing){t=Math.min(r.end,t+Math.min((now-last)/1000,.1)*Number($('playback').value));if(t>=r.end){playing=false;$('play').textContent='↻ Replay';}draw();}else view?.update(t);last=now;requestAnimationFrame(frame);}requestAnimationFrame(frame);
function download(name,body,type){const url=URL.createObjectURL(new Blob([body],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),2000);}
$('export').onclick=()=>download('cocoon-experiment.json',JSON.stringify({schemaVersion:1,model:'constant-pressure screening v0.1',createdAt:new Date().toISOString(),assumptions:p,results:r,telemetryCsv:csv(r),limitations:'Synthetic timing, prescribed pose, assumed vehicle transfer. No injury prediction or safety qualification.'},null,2),'application/json');
function tab(name){$('sim').hidden=name!=='sim';$('research').hidden=name!=='research';document.querySelectorAll('[data-tab]').forEach(b=>b.classList.toggle('active',b.dataset.tab===name));}document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>tab(b.dataset.tab));$('notes-link').onclick=e=>{e.preventDefault();tab('research');};
const sources=[['Bosch BMI270','Wearable motion IMU: up to ±16 g and ±2000°/s. Two structural nodes are candidates; impact clipping still needs evaluation.','https://www.bosch-sensortec.com/en/products/motion-sensors/imus/bmi270'],['Analog Devices ADXL375','Separate high-g measurement candidate (±200 g). Range alone does not validate impact measurement.','https://www.analog.com/en/products/adxl375.html'],['ST STM32U575/585','Local controller candidate. Watchdog, diagnostics and independent actuation architecture still require design.','https://www.st.com/en/microcontrollers-microprocessors/stm32u575-585.html'],['Honeywell ABP2 family','Pressure-feedback candidate; choose gauge range, ports, media compatibility and response from the exact part datasheet.','https://prod-edam.honeywell.com/content/dam/honeywell-edam/sps/siot/en-us/products/sensors/pressure-sensors/board-mount-pressure-sensors/basic-abp2-series/documents/sps-siot-abp2-series-datasheet-32350268-en.pdf'],['Textiles, tethers and inflators','Coated textile chambers and inextensible tethers are design candidates. No inflator is selected: volume, flow, timing and seam tests must come first.','./docs/ENGINEERING.md'],['KFall dataset paper','A useful detection baseline, not representative evidence for roofers or pedestrian crashes. No dataset is bundled or model trained here.','https://www.frontiersin.org/journals/aging-neuroscience/articles/10.3389/fnagi.2021.692865/full']];
$('sources').innerHTML=sources.map(([name,desc,url])=>`<div class="source"><a href="${url}" target="_blank" rel="noreferrer">${name} ↗</a><p>${desc}</p></div>`).join('');rebuild();
